In [1]:
!pip install noisereduce
!pip install praat-parselmouth
!pip install --upgrade librosa
!pip install librosa scipy
!pip install pysptk
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 82.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 461.9/461.9 kB 10.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for pysptk: filename=pysptk-1.0.1-cp310-cp310-linux_x86_64.whl size=1241912 sha256=5e0102debad2fe941dac697bfddf4e39de292b7e6c5de7afd97db01e22b769c0
  Stored in directory: /root/.cache/pip/wheels/ba/c2/7f/73c54e1795eeca8f995f95474c8290b78ee0a6306412dc934f
Successfully built pysptk


In [2]:
import numpy as np
import os
import pandas as pd
import re
import librosa
import parselmouth
from parselmouth.praat import call
import scipy.stats as stats
import scipy
import pysptk
from scipy.io import wavfile
from tqdm import tqdm
from google.colab import drive

# Scikit-learn imports
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import f1_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder

# TensorFlow and Keras imports
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.utils import to_categorical
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
# Proceed with splitting the data and training the model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import Layer
import tensorflow.keras.backend as K
from sklearn.model_selection import KFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Bidirectional
from tensorflow.keras.optimizers import Adam
import numpy as np
from tensorflow.keras.layers import Layer
import tensorflow.keras.backend as K

# Visualization imports
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

# Google Colab specific
drive.mount('/content/drive')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


Mounted at /content/drive


In [3]:
import re
import nltk
from transformers import BertTokenizer, BertModel
import torch
from torch import nn, optim
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from torch.utils.data import DataLoader, Dataset
import numpy as np

# Download NLTK tokenizer
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [4]:
df = pd.read_csv("/content/drive/Shared drives/CS298/CS 297/IEMOCAP/IEMOCAP_MAJOR_LABELLED.csv")

In [ ]:
df.head()

Session       Conversation  \
0  Session4  Ses04F_script03_1   
1  Session4  Ses04F_script03_1   
2  Session4  Ses04F_script03_1   
3  Session4  Ses04F_script03_1   
4  Session4  Ses04F_script03_1   

                                          Audio_Path              Speaker_id  \
0  /content/drive/My Drive/CS 297/IEMOCAP/Session...  Ses04F_script03_1_M001   
1  /content/drive/My Drive/CS 297/IEMOCAP/Session...  Ses04F_script03_1_M002   
2  /content/drive/My Drive/CS 297/IEMOCAP/Session...  Ses04F_script03_1_F005   
3  /content/drive/My Drive/CS 297/IEMOCAP/Session...  Ses04F_script03_1_M006   
4  /content/drive/My Drive/CS 297/IEMOCAP/Session...  Ses04F_script03_1_F006   

                                         Transcript         Time_Frame  \
0                                         I wonder.  008.6300-009.6700   
1                             It must be them then.  011.4300-012.7900   
2                Ahh.  It sent shivers up my spine.  025.9111-030.4663   
3  What shall we do if they suddenly walk in on us?  029.8095-033.1781   
4                               Behave exquisitely.  032.8800-034.9200   

                                 Audio_Uttrance_Path  \
0  /content/drive/My Drive/CS 297/IEMOCAP/Session...   
1  /content/drive/My Drive/CS 297/IEMOCAP/Session...   
2  /content/drive/My Drive/CS 297/IEMOCAP/Session...   
3  /content/drive/My Drive/CS 297/IEMOCAP/Session...   
4  /content/drive/My Drive/CS 297/IEMOCAP/Session...   

                                category most_repeated_label  
0            ['Fear', 'Fear', 'Excited']                fear  
1            ['Fear', 'Fear', 'Excited']                fear  
2  ['Frustration', 'Excited', 'Excited']             excited  
3  ['Frustration', 'Excited', 'Excited']             excited  
4    ['Excited', 'Happiness', 'Excited']             excited

In [ ]:
print(type(df['most_repeated_label'].iloc[0]))

<class 'str'>


In [ ]:
import ast

# Apply ast.literal_eval to convert string to list
df['category'] = df['category'].apply(lambda x: ast.literal_eval(x))
print(type(df['category'].iloc[0]))


<class 'list'>


In [ ]:
df['category'].iloc[0]

['Frustration', 'Fear', 'Excited']

In [ ]:
import pandas as pd
from collections import Counter

# Step 1: Copy df to new_df
new_df = df.copy()

# Step 2: Function to find the most repeated label (case insensitive)
def find_most_repeated_label(label_list):
    # Convert all items to lowercase
    lower_case_labels = [label.lower() for label in label_list]

    # Count the occurrences of each label
    label_counts = Counter(lower_case_labels)

    # Find the label(s) that repeat more than once
    most_common_label, count = label_counts.most_common(1)[0]  # Get the most common label

    # If it repeats more than once, return it, otherwise return None
    if count > 1:
        return most_common_label
    else:
        return None

# Step 3: Apply the function to each row in the 'category' column and create a new column 'most_repeated_label'
new_df['most_repeated_label'] = new_df['category'].apply(lambda x: find_most_repeated_label(x))


In [ ]:
new_df.head()

Session       Conversation  \
0  Session4  Ses04F_script03_1   
1  Session4  Ses04F_script03_1   
2  Session4  Ses04F_script03_1   
3  Session4  Ses04F_script03_1   
4  Session4  Ses04F_script03_1   

                                          Audio_Path              Speaker_id  \
0  /content/drive/My Drive/CS 297/IEMOCAP/Session...  Ses04F_script03_1_M000   
1  /content/drive/My Drive/CS 297/IEMOCAP/Session...  Ses04F_script03_1_F000   
2  /content/drive/My Drive/CS 297/IEMOCAP/Session...  Ses04F_script03_1_M001   
3  /content/drive/My Drive/CS 297/IEMOCAP/Session...  Ses04F_script03_1_F001   
4  /content/drive/My Drive/CS 297/IEMOCAP/Session...  Ses04F_script03_1_M002   

                                          Transcript         Time_Frame  \
0                                          Good God.  006.2551-008.1400   
1                            Do you think it's them?  007.7500-009.1900   
2                                          I wonder.  008.6300-009.6700   
3  Nobody knows we're here except Freda and she w...  009.2300-011.8600   
4                              It must be them then.  011.4300-012.7900   

  Major_emotion                                Audio_Uttrance_Path  \
0  Frustration   /content/drive/My Drive/CS 297/IEMOCAP/Session...   
1  Frustration   /content/drive/My Drive/CS 297/IEMOCAP/Session...   
2         Fear   /content/drive/My Drive/CS 297/IEMOCAP/Session...   
3  Frustration   /content/drive/My Drive/CS 297/IEMOCAP/Session...   
4         Fear   /content/drive/My Drive/CS 297/IEMOCAP/Session...   

                        Major_Emotion Major  ... Dominance  \
0  ['Fear', 'Excited', 'Frustration']  Fear  ...    [4, 4]   
1  ['Fear', 'Excited', 'Frustration']  Fear  ...    [3, 4]   
2         ['Fear', 'Excited', 'Fear']  Fear  ...    [3, 4]   
3  ['Fear', 'Excited', 'Frustration']  Fear  ...    [3, 4]   
4         ['Fear', 'Excited', 'Fear']  Fear  ...    [3, 4]   

                                           dimension  \
0  [{'arousal': 3.0, 'valence': 3.0, 'dominance':...   
1  [{'arousal': 3.5, 'valence': 2.0, 'dominance':...   
2  [{'arousal': 3.0, 'valence': 3.0, 'dominance':...   
3  [{'arousal': 4.0, 'valence': 2.5, 'dominance':...   
4  [{'arousal': 3.0, 'valence': 2.5, 'dominance':...   

                       category  act  val  dom New_Category Final_class  \
0  [Frustration, Fear, Excited]  2,4  3,3  4,4      Nervous         NaN   
1  [Frustration, Fear, Excited]  2,5  2,2  3,4      Nervous         NaN   
2         [Fear, Fear, Excited]  2,4  3,3  3,4      Nervous         NaN   
3  [Frustration, Fear, Excited]  3,5  3,2  3,4      Nervous         NaN   
4         [Fear, Fear, Excited]  2,4  2,3  3,4      Nervous         NaN   

  Unnamed: 20 most_repeated_label  
0         NaN                None  
1         NaN                None  
2         NaN                fear  
3         NaN                None  
4         NaN                fear  

[5 rows x 22 columns]

In [ ]:
new_df = new_df.drop(columns=['act', 'val', 'dom', 'New_Category', 'Final_class', 'Unnamed: 20'])


In [ ]:
new_df = new_df.drop(columns=['Major_Emotion', 'Major_emotion','Major', 'Arousal', 'Valence', 'Dominance', 'dimension'])


In [ ]:
new_df = new_df[new_df['most_repeated_label'].notna()]

In [ ]:
len(new_df)

7766

In [ ]:
label_counts = new_df['most_repeated_label'].value_counts()

print(label_counts)

most_repeated_label
frustration    2026
neutral        1710
excited        1174
sadness        1075
anger          1042
happiness       586
surprise        102
fear             34
other            14
disgust           3
Name: count, dtype: int64


In [ ]:
import pandas as pd
new_df = df.copy()
# Modify the labels according to the merging criteria
new_df['most_repeated_label'] = new_df['most_repeated_label'].replace({
    #'frustration': 'anger',   # Merge 'frustration' into 'anger'
    'excited': 'happy',       # Merge 'excited' into 'happy'
    'happiness': 'happy'      # Merge 'happiness' into 'happy'
})

# Drop rows with the labels: 'surprise', 'fear', 'other', and 'disgust'
new_df = new_df[~new_df['most_repeated_label'].isin(['surprise', 'fear', 'other', 'disgust','frustration'])]

# Print updated value counts to verify
print(new_df['most_repeated_label'].value_counts())


most_repeated_label
happy      1760
neutral    1710
sadness    1075
anger      1042
Name: count, dtype: int64


In [ ]:
#new_df.to_csv('IEMOCAP_MAJOR_LABELLED.csv', index=False)

In [ ]:
# Preprocessing function
def preprocess(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'[^\w\s]', '', text)  # Remove punctuation
    tokens = nltk.word_tokenize(text)  # Tokenize text
    return " ".join(tokens)

In [ ]:
new_df['cleaned_text'] = new_df['Transcript'].apply(preprocess)

In [ ]:
# Encode the target labels
label_encoder = LabelEncoder()
new_df['encoded_label'] = label_encoder.fit_transform(new_df['most_repeated_label'])

In [ ]:
from tqdm import tqdm
#BERT tokenizer to convert text to BERT-compatible tokens
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

class EmotionDataset(Dataset):
    def __init__(self, texts, labels):
        self.texts = texts
        self.labels = labels

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]
        encoding = tokenizer.encode_plus(
            text,
            add_special_tokens=True,
            max_length=128,
            return_token_type_ids=False,
            padding='max_length',
            truncation=True,
            return_attention_mask=True,
            return_tensors='pt'
        )
        return {
            'input_ids': encoding['input_ids'].flatten(),
            'attention_mask': encoding['attention_mask'].flatten(),
            'label': torch.tensor(label, dtype=torch.long)
        }

# Define the model
class BERTEmotionClassifier(nn.Module):
    def __init__(self, n_classes):
        super(BERTEmotionClassifier, self).__init__()
        self.bert = BertModel.from_pretrained('bert-base-uncased')
        self.drop = nn.Dropout(p=0.3)
        self.out = nn.Linear(self.bert.config.hidden_size, n_classes)

    def forward(self, input_ids, attention_mask):
        pooled_output = self.bert(
            input_ids=input_ids,
            attention_mask=attention_mask
        )['pooler_output']
        output = self.drop(pooled_output)
        return self.out(output)



# Training function
def train_epoch(model, data_loader, loss_fn, optimizer, device):
    model = model.train()
    losses = []
    correct_predictions = 0
    loop = tqdm(data_loader, leave=False)

    for batch in data_loader:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['label'].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        loss = loss_fn(outputs, labels)
        _, preds = torch.max(outputs, dim=1)
        correct_predictions += torch.sum(preds == labels)
        losses.append(loss.item())

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        # Update tqdm description with current loss
        loop.set_description(f"Loss: {loss.item():.4f}")

    return correct_predictions.double() / len(data_loader.dataset), np.mean(losses)



# Evaluation
def eval_model(model, data_loader, device):
    model = model.eval()
    correct_predictions = 0
    predictions = []
    true_labels = []

    with torch.no_grad():
        for batch in data_loader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['label'].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            _, preds = torch.max(outputs, dim=1)
            correct_predictions += torch.sum(preds == labels)
            predictions.extend(preds.cpu().numpy())
            true_labels.extend(labels.cpu().numpy())
        # Calculate accuracy
        accuracy = correct_predictions.double() / len(data_loader.dataset)

        # Calculate F1 score (macro or weighted depending on your needs)
        f1 = f1_score(true_labels, predictions, average='weighted')

    return accuracy, f1, predictions, true_labels


/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [ ]:
# Split the data into training and testing sets
train_texts, test_texts, train_labels, test_labels = train_test_split(new_df['cleaned_text'], new_df['encoded_label'], test_size=0.2, random_state=42)

train_dataset = EmotionDataset(train_texts.tolist(), train_labels.tolist())
test_dataset = EmotionDataset(test_texts.tolist(), test_labels.tolist())

train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=4)

In [ ]:
# Initialize the model
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = BERTEmotionClassifier(n_classes=len(label_encoder.classes_))
model = model.to(device)

# Loss function and optimizer
optimizer = optim.Adam(model.parameters(), lr=2e-5)
loss_fn = nn.CrossEntropyLoss()

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [ ]:
for epoch in range(5):  # For demo, you can increase this for better performance
    print(f'Epoch {epoch + 1}/{2}')
    train_acc, train_loss = train_epoch(model, train_loader, loss_fn, optimizer, device)
    print(f'Train accuracy: {train_acc}, Loss: {train_loss}')

Epoch 1/2


Train accuracy: 0.5390467666144552, Loss: 1.0794441892044062
Epoch 2/2


Train accuracy: 0.7531886328037593, Loss: 0.6370287163346366
Epoch 3/2


Train accuracy: 0.8435891698366524, Loss: 0.42624772012680234
Epoch 4/2


Train accuracy: 0.876706198254643, Loss: 0.31989011532283007
Epoch 5/2


Train accuracy: 0.895949876929962, Loss: 0.2659812551658194


In [ ]:
# Evaluate on test set
test_acc, preds, true_labels = eval_model(model, test_loader, device)
print(f'Test Accuracy: {test_acc}')

# Display classification report
from sklearn.metrics import classification_report
print(classification_report(true_labels, preds, target_names=label_encoder.classes_))

Test Accuracy: 0.6762075134168157
              precision    recall  f1-score   support

       anger       0.73      0.68      0.71       193
       happy       0.67      0.80      0.73       360
     neutral       0.60      0.58      0.59       333
     sadness       0.76      0.61      0.68       232

    accuracy                           0.68      1118
   macro avg       0.69      0.67      0.68      1118
weighted avg       0.68      0.68      0.67      1118



In [ ]:
# Evaluate on test set
test_acc, preds, true_labels = eval_model(model, test_loader, device)
print(f'Test Accuracy: {test_acc}')

# Display classification report
from sklearn.metrics import classification_report
print(classification_report(true_labels, preds, target_names=label_encoder.classes_))

Test Accuracy: 0.6762075134168157
              precision    recall  f1-score   support

       anger       0.73      0.68      0.71       193
       happy       0.67      0.80      0.73       360
     neutral       0.60      0.58      0.59       333
     sadness       0.76      0.61      0.68       232

    accuracy                           0.68      1118
   macro avg       0.69      0.67      0.68      1118
weighted avg       0.68      0.68      0.67      1118



In [ ]:
from sklearn.metrics import confusion_matrix

# Number of folds
n_splits = 5

# Initialize KFold
kf = KFold(n_splits=n_splits, shuffle=True, random_state=42)

# Create a list to store results for each fold
fold_accuracies = []
fold_f1 = []
# Convert text and labels to lists for cross-validation purposes
texts = new_df['cleaned_text'].tolist()
labels = new_df['encoded_label'].tolist()

# Check the size of the data
print(f"Number of samples in texts: {len(texts)}")
print(f"Number of samples in labels: {len(labels)}")
num_epoch = 10
# Begin 5-Fold Cross-Validation
for fold, (train_index, val_index) in enumerate(kf.split(texts)):
    print(f"Fold {fold+1}/{n_splits}")

    # Debug: Check the sizes of the indices
    print(f"Train indices size: {len(train_index)}, Val indices size: {len(val_index)}")

    # Split the data into training and validation sets for this fold
    try:
        train_texts = [texts[i] for i in train_index]
        val_texts = [texts[i] for i in val_index]
        train_labels = [labels[i] for i in train_index]
        val_labels = [labels[i] for i in val_index]
    except IndexError as e:
        print(f"IndexError: {e}")
        print(f"Text size: {len(texts)}, Label size: {len(labels)}")
        break  # Break the loop if there's an issue with indexing

    # Create the datasets and dataloaders for this fold
    train_dataset = EmotionDataset(train_texts, train_labels)
    val_dataset = EmotionDataset(val_texts, val_labels)

    train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=4)

    # Reinitialize the model for each fold
    model = BERTEmotionClassifier(n_classes=len(label_encoder.classes_))
    model = model.to(device)

    # Reinitialize the optimizer and loss function for each fold
    optimizer = optim.Adam(model.parameters(), lr=2e-5)
    loss_fn = nn.CrossEntropyLoss()

    # Train for a few epochs (adjust as necessary)
    for epoch in range(10):  # Adjust epochs as needed
        print(f'Epoch {epoch + 1}/3')

        # Training step
        train_acc, train_loss = train_epoch(model, train_loader, loss_fn, optimizer, device)

        # Validation step
        val_acc, val_f1, val_preds, val_true_labels = eval_model(model, val_loader, device)

        print(f'Train accuracy: {train_acc}, Train loss: {train_loss}')
        print(f'Validation accuracy: {val_acc}')

    # Generate and print confusion matrix for this fold
    cm = confusion_matrix(val_true_labels, val_preds)
    print(f'Confusion Matrix for Fold {fold + 1}:\n', cm)


    # Store the validation accuracy for this fold
    fold_accuracies.append(val_acc.item())
    fold_f1.append(val_f1)
    print('********************************************')
# After all folds are completed, calculate and display the average results
avg_accuracy = np.mean(fold_accuracies)
avg_f1 = np.mean(fold_f1)
print(f"\nAverage Validation Accuracy across {n_splits} folds: {avg_accuracy}")
print(f"\nAverage Validation F1 across {n_splits} folds: {avg_f1}")



Number of samples in texts: 5587
Number of samples in labels: 5587
Fold 1/5
Train indices size: 4469, Val indices size: 1118
Epoch 1/3


Train accuracy: 0.564779592750056, Train loss: 1.036753500336931
Validation accuracy: 0.6699463327370304
Epoch 2/3


Train accuracy: 0.7719847840680242, Train loss: 0.612238131635131
Validation accuracy: 0.7048300536672629
Epoch 3/3


Train accuracy: 0.8534347728798388, Train loss: 0.4016581814251307
Validation accuracy: 0.6976744186046512
Epoch 4/3


Train accuracy: 0.8878943835309913, Train loss: 0.30245989760007436
Validation accuracy: 0.6994633273703041
Epoch 5/3


Train accuracy: 0.8932647124636384, Train loss: 0.2610264728337273
Validation accuracy: 0.6958855098389982
Epoch 6/3


Train accuracy: 0.9107182814947415, Train loss: 0.22182943777225775
Validation accuracy: 0.7003577817531306
Epoch 7/3


Train accuracy: 0.9118371000223763, Train loss: 0.20754109083535108
Validation accuracy: 0.7021466905187835
Epoch 8/3


Train accuracy: 0.9145222644886999, Train loss: 0.204153797079587
Validation accuracy: 0.7030411449016101
Epoch 9/3


Train accuracy: 0.9194450660102931, Train loss: 0.19077002894357623
Validation accuracy: 0.7003577817531306
Epoch 10/3


Train accuracy: 0.919892593421347, Train loss: 0.178872260104773
Validation accuracy: 0.7012522361359571
Confusion Matrix for Fold 1:
 [[136  17  27  13]
 [  6 267  71  16]
 [ 28  51 227  27]
 [  8  26  44 154]]
********************************************
Fold 2/5
Train indices size: 4469, Val indices size: 1118
Epoch 1/3


Train accuracy: 0.539941821436563, Train loss: 1.069486757110611
Validation accuracy: 0.6753130590339893
Epoch 2/3


Train accuracy: 0.7612441262027299, Train loss: 0.6427997433762058
Validation accuracy: 0.6878354203935599
Epoch 3/3


Train accuracy: 0.8567912284627434, Train loss: 0.4095514562907287
Validation accuracy: 0.7021466905187835
Epoch 4/3


Train accuracy: 0.8881181472365182, Train loss: 0.30916751102625173
Validation accuracy: 0.6949910554561718
Epoch 5/3


Train accuracy: 0.895949876929962, Train loss: 0.2675512444874778
Validation accuracy: 0.6985688729874776
Epoch 6/3


Train accuracy: 0.9122846274334303, Train loss: 0.22343980756772377
Validation accuracy: 0.6878354203935599
Epoch 7/3


Train accuracy: 0.9169836652494965, Train loss: 0.2128865416398087
Validation accuracy: 0.6905187835420393
Epoch 8/3


Train accuracy: 0.913403445961065, Train loss: 0.20187036585708754
Validation accuracy: 0.6815742397137746
Epoch 9/3


Train accuracy: 0.9160886104273886, Train loss: 0.1938459573678355
Validation accuracy: 0.6923076923076923
Epoch 10/3


Train accuracy: 0.9189975385992392, Train loss: 0.17705121848265531
Validation accuracy: 0.6967799642218246
Confusion Matrix for Fold 2:
 [[149   9  22  14]
 [ 11 265  42  35]
 [ 38  55 219  64]
 [ 12  17  20 146]]
********************************************
Fold 3/5
Train indices size: 4470, Val indices size: 1117
Epoch 1/3


Train accuracy: 0.5451901565995526, Train loss: 1.0590020687067765
Validation accuracy: 0.6893464637421665
Epoch 2/3


Train accuracy: 0.7695749440715884, Train loss: 0.6241110924611365
Validation accuracy: 0.683974932855864
Epoch 3/3


Train accuracy: 0.8516778523489933, Train loss: 0.4053260656506863
Validation accuracy: 0.7009847806624888
Epoch 4/3


Train accuracy: 0.8809843400447428, Train loss: 0.32072262504939425
Validation accuracy: 0.7036705461056401
Epoch 5/3


Train accuracy: 0.8979865771812081, Train loss: 0.26297174498904496
Validation accuracy: 0.6911369740376007
Epoch 6/3


Train accuracy: 0.9004474272930649, Train loss: 0.2441146708551123
Validation accuracy: 0.6803939122649956
Epoch 7/3


Train accuracy: 0.9147651006711409, Train loss: 0.20497572969502398
Validation accuracy: 0.6929274843330349
Epoch 8/3


Train accuracy: 0.9161073825503356, Train loss: 0.1982127573511485
Validation accuracy: 0.6974037600716204
Epoch 9/3


Train accuracy: 0.9266219239373602, Train loss: 0.17334023004212193
Validation accuracy: 0.7009847806624888
Epoch 10/3


Train accuracy: 0.9246085011185683, Train loss: 0.17899013964601124
Validation accuracy: 0.7036705461056401
Confusion Matrix for Fold 3:
 [[167  16  28   8]
 [ 12 293  45  13]
 [ 40  59 205  27]
 [ 10  25  48 121]]
********************************************
Fold 4/5
Train indices size: 4470, Val indices size: 1117
Epoch 1/3


Train accuracy: 0.53668903803132, Train loss: 1.0689899915419452
Validation accuracy: 0.6696508504923904
Epoch 2/3


Train accuracy: 0.7633109619686801, Train loss: 0.6377469518959975
Validation accuracy: 0.7054610564010743
Epoch 3/3


Train accuracy: 0.8476510067114095, Train loss: 0.4213468610210767
Validation accuracy: 0.7126230975828111
Epoch 4/3


Train accuracy: 0.894854586129754, Train loss: 0.29544216435159387
Validation accuracy: 0.7170993733213966
Epoch 5/3


Train accuracy: 0.896420581655481, Train loss: 0.25811487895208335
Validation accuracy: 0.7126230975828111
Epoch 6/3


Train accuracy: 0.9073825503355705, Train loss: 0.23327179300729586
Validation accuracy: 0.6812891674127126
Epoch 7/3


Train accuracy: 0.9147651006711409, Train loss: 0.20724985371543717
Validation accuracy: 0.7144136078782453
Epoch 8/3


Train accuracy: 0.9190156599552572, Train loss: 0.19397084213663535
Validation accuracy: 0.6911369740376007
Epoch 9/3


Train accuracy: 0.9214765100671142, Train loss: 0.18193873018744836
Validation accuracy: 0.7036705461056401
Epoch 10/3


Train accuracy: 0.9178970917225951, Train loss: 0.18735518263067094
Validation accuracy: 0.711727842435094
Confusion Matrix for Fold 4:
 [[153  11  21  16]
 [ 15 263  35  32]
 [ 30  53 199  61]
 [ 10  14  24 180]]
********************************************
Fold 5/5
Train indices size: 4470, Val indices size: 1117
Epoch 1/3


Train accuracy: 0.5279642058165548, Train loss: 1.075525679893805
Validation accuracy: 0.6902417188898836
Epoch 2/3


Train accuracy: 0.7568232662192393, Train loss: 0.6280808168061891
Validation accuracy: 0.7054610564010743
Epoch 3/3


Train accuracy: 0.8494407158836689, Train loss: 0.41339373658452855
Validation accuracy: 0.7162041181736795
Epoch 4/3


Train accuracy: 0.8863534675615212, Train loss: 0.2997449939226655
Validation accuracy: 0.7054610564010743
Epoch 5/3


Train accuracy: 0.9, Train loss: 0.25468740129634265
Validation accuracy: 0.7000895255147717
Epoch 6/3


Train accuracy: 0.9105145413870246, Train loss: 0.22304242111612127
Validation accuracy: 0.7045658012533572
Epoch 7/3


Train accuracy: 0.90917225950783, Train loss: 0.21911503788465317
Validation accuracy: 0.6866606982990152
Epoch 8/3


Train accuracy: 0.9201342281879195, Train loss: 0.19471899123450245
Validation accuracy: 0.702775290957923
Epoch 9/3


Train accuracy: 0.9190156599552572, Train loss: 0.1896347856435534
Validation accuracy: 0.7009847806624888
Epoch 10/3


Train accuracy: 0.9178970917225951, Train loss: 0.19112601329851353
Validation accuracy: 0.6866606982990152
Confusion Matrix for Fold 5:
 [[174  10  26  25]
 [ 13 252  38  36]
 [ 36  52 178  61]
 [  6  25  22 163]]
********************************************

Average Validation Accuracy across 5 folds: 0.7000182574395062

Average Validation F1 across 5 folds: 0.6991866897078287
